name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on: # <--- Pastikan ini dan baris di bawahnya tidak dikomentari
  push:
    branches:
      - main # Workflow ini akan berjalan setiap kali ada push ke branch 'main'

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Sebaiknya update ke versi terbaru, misal @v3 atau @v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install dependencies # Langkah ini mungkin perlu disesuaikan
        run: npm install # Jika package.json ada di root, jika di ./frontend, tetap pakai working-directory
        working-directory: ./frontend # Jika package.json ada di dalam ./frontend

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend