name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Disarankan menggunakan @v3 atau @v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./frontend

      # Langkah BARU: Membuat file vercel.json secara dinamis
      - name: Create vercel.json to define correct root
        run: |
          echo '{
            "version": 2,
            "rootDirectory": "."
          }' > vercel.json
        working-directory: ./frontend # Pastikan ini dibuat di dalam direktori frontend

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend